---
apiVersion: v1
kind: ImageStream
metadata:
  name: gameoflife
  labels:
    application: gameoflife
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: gameoflife
spec:
  lookupPolicy:
    local: true
  output:
    to:
      kind: ImageStreamTag
      name: gameoflife:local-build
  source: 
    git:
      uri: https://github.com/mmgaggle/metrodemo.git
      branch: kyle
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8/python-38
